#always formated as so each comparison has an item called column_name. This MUST be called column_name. It has one item.
#then there are 2 more items, this should be named as you want the output to be named. Only two. The name must NEVER contain and UnderScore or you will have
#problems. I suggest camelCase names, but doesn't really matter as long as you can interpret them. Throughout the file they have to be unique.
#each of these two items has as many idenitifiers as you like, but they must be
#valid identifiers from the column_name column in the sample_csv. The first identifier is always the baseline group
AstroNonActivatedControlVersusActivatedControl:
  column_name:
    - group
  AstroNonActivatedControl:
    - Astro_NonActivated_Control
  AstroActivatedControl:
    - Astro_Activated_Control
AstroNonActivatedControlVersusNonActivatedTDP43KD:
  column_name:
    - group
  AstroNonActivatedControl:
    - Astro_NonActivated_Control
  AstroNonActivatedTDP43KD:
    - Astro_NonActivated_TDP43KD
AstroActivatedControlVersusActivatedTDP43KD:
  column_name:
    - group
  AstroActivatedControl:
    - Astro_Activated_Control
  AstroActivatedTDP43KD:
    - Astro_Activated_TDP43KD
AstroNonActivatedTDP43KDVersusActivatedTDP43KD:
  column_name:
    - group
  AstroNonActivatedTDP43KD:
    - Astro_NonActivated_TDP43KD
  AstroActivatedTDP43KD:
    - Astro_Activated_TDP43KD
MicrogliaNonActivatedControlVersusActivatedControl:
  column_name:
    - group
  MicrogliaNonActivatedControl:
    - Microglia_NonActivated_Control
  MicrogliaActivatedControl:
    - Microglia_Activated_Control
MicrogliaNonActivatedControlVersusNonActivatedTDP43KD:
  column_name:
    - group
  MicrogliaNonActivatedControl:
    - Microglia_NonActivated_Control
  MicrogliaNonActivatedTDP43KD:
    - Microglia_NonActivated_TDP43KD
MicrogliaActivatedControlVersusActivatedTDP43KD:
  column_name:
    - group
  MicrogliaActivatedControl:
    - Microglia_Activated_Control
  MicrogliaActivatedTDP43KD:
    - Microglia_Activated_TDP43KD
MicrogliaNonActivatedTDP43KDVersusActivatedTDP43KD:
  column_name:
    - group
  MicrogliaNonActivatedTDP43KD:
    - Microglia_NonActivated_TDP43KD
  MicrogliaActivatedTDP43KD:
    - Microglia_Activated_TDP43KD